postgresql:
  image:
    tag: "16"
  auth:
    username: pguser
    database: mydb
    existingSecret: postgres-secret
    secretKeys:
      userPasswordKey: password
  primary:
    persistence:
      enabled: false